name: project.py

on:
  schedule:
    - cron: '0 0 * * 5' # At 00:00 on Friday
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Scrapy spiders
      - name: execute mealdb Scrapy spider 
        run: scrapy crawl mealdb -O mealdb.json
        working-directory: ./landing_zone/collectors/Mealdb/mealscraper

      - name: execute approvedfood Scrapy spider 
        run: scrapy crawl approvedfood_groceries -O Approvedfood.json
        working-directory: ./landing_zone/collectors/ApprovedFoodUK/approvedfood_scraper

      # Python scripts
      # - name: execute eat_by_date.py script 
      #   run: python eat_by_date.py
      #   working-directory: ./landing_zone/collectors/eat_by_date

      # - name: execute flipkart.py script 
      #   run: python scrap_flipkart.py
      #   working-directory: ./Flipkart
      
      # - name: Notify Slack
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: workflow,job,commit,repo,ref,author,took 
      #     text: 'Job done. Workflow: ${{ github.workflow }}. Status: ${{ job.status }}.'
      #     webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      #   if: always() 
      
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and Push Changes to the Triggered Branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          if git diff --quiet --staged; then
            echo "No changes to commit."
          else
            git commit -m "Update JSON outputs"
            git push origin HEAD
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
